### ISSUE TITLE
After installation v1.5.2: This app was terminated unexpectedly

### ISSUE THREAD

**Issue by dirkg173** [TedTolboom/com.mcohome#62]
Hi @TedTolboom,
after installation of the test version v1.5.2, the app was terminated unexpectedly.
Didn't notice it right away because there were no red exclamation marks displayed on the devices (MH7H).
Because it was not possible to send the login content from the app (414 Request-URI Too Large), I took screenshots and tried to copy out the text:

Stacktrace:
[err] 2022-11-02 13:09:22 [ManagerDrivers] [Driver:MH7H] Error Initializing Device: /drivers/MH7H/device.js:8
await super. async onNodeInit();

SyntaxError: Unexpected identifier
at Object. compileFunction (node: vm:352:18)
at wrapSafe (node: internal/modules/cjs/loader:1032:15)
at Module._compile (node: internal/modules/cjs/loader:1067:27)
at Object. Module. extensions..js (node: internal/modules/cis/loader:1157:10)
at Module.load (node: internal/modules/cjs/loader:981:32)
at Function. Module._load (node: internal/modules/cis/loader:822:12)
at Module. require (node: internal/modules/cjs/loader:1005:19)
at Module.require(/opt/homey-client/system/manager/ManagerApps/AppProcess/nodemodules/homey-apps-sdk-v3/index.js:1:183)
at require(node:internal/modules/cjs/helpers:102:18)
at Object. importAbsolutePathIfExists(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/
Util.js:1:1679)
[err] 2022-11-02 13:09:22 (ManagerDrivers] [Driver: MH7H] Error Initializing Device: /drivers/MH7H/device.js:8
await super. async onNodeInit () ;

SyntaxError: Unexpected identifier
at Object. compileFunction (node: vm:352:18)
at wrapSafe (node: internal/modules/cjs/loader:1032:15)
at Module._ compile (node: internal/modules/cis/loader:1067:27)
at Object. Module._extensions..js (node: internal/modules/cjs/loader:1157:10)
at Module.load (node: internal/modules/cis/loader:981:32)
at Function. Module. load (node: internal/modules/cis/loader:822:12)
at Module. require (node: internal/modules/cjs/loader:1005:19)
at Module.require(/opt/homey-client/system/manager/ManagerApps/AppProcess/nodemodules/homey-apps-sdk-v3/index.js:1:183)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.importAbsolutePathIfExists(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/
Util.js:1:1679)
[err] 2022-11-02 13:09:22 [ManagerDrivers] [Driver:MH7H] Error Initializing Device: /drivers/MH7H/device.js:8
await super.async onNodeInit();

SyntaxError: Unexpected identifier
at Object. compileFunction (node: vm: 352:18)
at wrapSafe (node: internal/modules/cis/loader:1032:15)
at Module. _compile (node: internal/modules/cjs/loader:1067:27)
at Object. Module. _extensions..js (node: internal/modules/cjs/loader:1157:10)
at Module. load (node: internal/modules/cjs/loader:981:32)
t Function. Module. load (node: internal/modules/cjs/loader:822:12)
at Module. require (node: internal/modules/cjs/loader:1005:19)
at Module.require(/opt/homey-client/system/manager/ManagerApps/AppProcess/nodemodules/homey-apps-sdk-v3/index.js:1:183)
at require(node:internal/modules/cjs/helpers:102:18)
Object.importAbsolutePathifExists(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/
Util.js:1:1679)
[err] 2022-11-02 13:09:22 [ManagerDrivers] [Driver: MH7H] Error Initializing Device: /drivers/MH7H/device.js:8
await super. async onNodeInit () ;

SyntaxError: Unexpected identifier
at Object. compileFunction (node: vm: 352:18)
at wrapSafe (node: internal/modules/cjs/loader:1032:15)
at Module. _compile (node: internal/modules/cjs/loader:1067:27)
at Object.Module._extensions..js(node:internal/modules/cjs/loader:1157:10)
at Module. load (node: internal/modules/cjs/loader:981:32)
at Function. Module. load (node: internal/modules/cjs/loader:822:12)
at Module. require (node: internal/modules/cjs/loader:1005:19)
at Module.require(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/index.js:1:183)
at require (node: internal/modules/cjs/helpers:102:18)
at Object. importAbsolutePathifExists(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/
Util.js:1:1679)
[err] 2022-11-02 13:09:22 [ManagerDrivers] [Driver: MH7H] Error Initializing Device: /drivers/MH7H/device.js:8
await super. async onNodeInit();

SyntaxError: Unexpected identifier
at Object. compileFunction (node: vm:352:18)
at wrapSafe (node: internal/modules/cjs/loader:1032:15)
at Module. _compile (node: internal/modules/cjs/loader:1067:27)
at Object. Module. extensions..js (node: internal/modules/cjs/loader:1157:10)
at Module. load (node: internal/modules/cjs/loader:981:32)
at Function. Module. load (node: internal/modules/cjs/loader:822:12)
Module. require (node: internal/modules/cjs/loader:1005:19)
at Module.require(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/index.js:1:183)
at require (node:internal/modules/cjs/helpers:102:18)
at Object. importAbsolutePathifExists(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/
Util.js:1:1679)
/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Driver.js:1
"use strict"; const path=require ("path"), Util=require("./Util.js"), Device-require("./Device.js"), SimpleClass=require (". /
SimpleClass.js"),s=-f),sClient=Symbol("client"),sDevicesById-Symbol("devicesById"),sReadyPromise-Symbol("readyPromise"),sDiscoveryStrategy-Symbol
("discoveryStrategy");class Driver extends SimpleClass{constructor(e,i,t,r,c)
(super(),this.id=e,this.homey=i,this.manifest=r,this[sClient]=t,this[sDevicesById]=(),this[sReadyPromise]-Promise.resolve().then(async()=>(await
Promise.all(c.map (async e=>(await this[s. _initDevice] (e). catch(e=›this. error ("Error Initializing Device:",e))})), await
this.onInit()}),this[sReadyPromise].catch(this.error),"string"==typeof
r.discovery&&(this[sDiscoveryStrategy]=i.discovery.getStrategy(r.discovery),this[s.__initDiscovery]())}async_onDeviceCreate(e)
{this. debug(" onDeviceCreate") ;const i=await this[s. initDevice] (e); return await i. ready(),i. onAdded() }async onDeviceDelete({deviceId:e})
(this._ debug ("_onDeviceDelete") ;const i=this.getDeviceByld(e); this[s.__uninitDevice] ((deviceld:e)) , await i. _onDeleted (), await i. onUninit () )
async_onDeviceRename((deviceId:e,...i})(returnthis.. _debug ("_onDeviceRename"), this. getDeviceById (e)._onRenamed (i) }async
_onDeviceSettings ((deviceId:e, ...i)) (return this.__debug("_onDeviceSettings"), this. getDeviceByld(e)._onSettings (i) }async
_onDeviceSetCapabilityValue({deviceld:e,...i}){return
this.__debug("_onDeviceSetCapabilityValue"),this.getDeviceById(e)._onSetCapabilityValue(i)}async
__initDevice ((deviceld:e, deviceData:i, deviceProperties:t}) (this. _debug ("_initDevice"); const s=(emit: async (i,t) =>this[sClient].emit(i,
{...t, deviceld:e}) };let r;if ("function"=-typeof this. onMapDeviceClass) (let s=new Device (i,e, this, (emit: async () =>(throw new Error ("Not Supported
In Driver.onMapDeviceClass")}),t);if(r=this.onMapDeviceClass(s),s.destroy(),s=void0,!(r&&r.prototypeinstanceofDevice))thrownew Error( The
class returned in '/drivers/$(this.id}/driver. js-›mapDeviceClass ()' must extend Device ) )else (const
e-path.join(this.homey.dir,"drivers",this.id,"device.js");if((r=awaitUtil.importAbsolutePathIfExists(e,(onModuleNotFound:()=>Device)))!
==Device&&! (r. prototype instanceof Device)) throw new Error ('The class exported in '/drivers/$(this.id}/device. js' must extend Device*) }const
c-new r(i,e, this, s,t); return this [sDevicesById][e]=c,c.on("__log", (...i)=>this .log (' [Device:$(e}] ,...i) ).on ("_error",
(...i)=>this.error(°[Device:$(e)}]°,...i)).on("__debug",(...i)=>this.debug(°[Device:$
fe}],...i)),this.ready().then(()=>C._onInit()).then(async()->(if(this[sDiscoveryStrategy])(awaitc.setUnavailable().catch(this.error);const
e-this[sDiscoveryStrategy].getDiscoveryResults();for(constiof
Object.values(e))c._onDiscoveryStrategyResult(i).catch(this.error)}}).Catch(e=>{c.setUnavailable().catch(this.error),this.error(e)}),c}
__uninitDevice ((deviceId:e)) (this.__debug("__uninitDevice"), delete this[sDevicesById][e]}__initDiscovery()
(this.ready().then(()=>(this[sDiscoveryStrategy].on("result",e=>(this.__debug("__onDiscoveryStrategyResult",e.id);for(constiof
this.getDevices())i._onDiscoveryStrategyResult(e).catch(this.error)})])}ready()(returnthis[sReadyPromise]}getDevices()(return
Object. values (this[sDevicesById]) }getDevice(e) (const i=Object. values (this[sDevicesById]).find(i=>Driver.isEqualDeviceData(i.getData(), e)); if(
i) throw new Error ("Could not get device by device data"); return i}getDeviceById(e) (const i=this [sDevicesById][e];if(!i) throw new Error ("Could
not get device by id") ;return i) getDiscoveryStrategy() (return this [sDiscoveryStrategyllasync onlnit() ()async onUninit () ()onPair (e)
{e.setHandler("list_devices",this.onPairListDevices.bind(this))}asynconPairListDevices()(return[]}staticisEqualDeviceData(e,i)(return
Util. deepCompare (e, i) )}Util. protectclass (Driver, s), module. exports=Driver;

Error: Could not det device bv id
In Dokumente und Dateinamen nach Text suchenpt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/11b/Driver.js:1:3452)
at Object. fromJsoN (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/SDK.js:334:23)
at Dopt homeorie l l e n t / oys t on manager/ManagerApps/Appprocess/node_nodules/homey-serializer/sro/Index.Js:168:29.
at (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-serializer/src/traverse.js:1:77)
atr(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-serializer/src/traverse.js:1:267)
at r (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-serializer/src/traverse.js:1:267)
at traverse(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-serializer/src/traverse.js:1:291)
at HomeySerializer.parse(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-serializer/src/index.js:164:12)
at HomeyClient._onMessage(/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:1077)
at IPCSocket. emit (node: events: 526:28)
Ausgangscode: 1
Ausgangssignal:

![IMG_3488](https://user-images.githubusercontent.com/40319629/200268669-75f41501-1fed-473d-9cac-ecc53247820c.PNG)
![IMG_3489](https://user-images.githubusercontent.com/40319629/200268682-460401e4-fd3e-4fa3-aea7-cdd3bfd95ba4.PNG)

**Comment by dirkg173** [comment]
Diagnostic Report no.: ef209077-3fac-4538-92fc-84d2bb650653

**Comment by TedTolboom** [comment]
Thanks for reporting Dirk. I notice the error.Will be able to fix on Friday at first opportunity.TedOn 7 Nov 2022, at 15:58, dirkg173 ***@***.***> wrote:﻿
Diagnostic Report no.: ef209077-3fac-4538-92fc-84d2bb650653

**Comment by TedTolboom** [comment]
Fixed in 1.5.3 currently in the test version of the App StoreOn 7 Nov 2022, at 17:00, Ted Tolboom ***@***.***> wrote:﻿Thanks for reporting Dirk. I notice the error.Will be able to fix on Friday at first opportunity.TedOn 7 Nov 2022, at 15:58, dirkg173 ***@***.***> wrote:﻿
Diagnostic Report no.: ef209077-3fac-4538-92fc-84d2bb650653
